export const SN_SUBSCRIPTION = 'subscription'
export const SUBSCRIPTION_ADD = SN_SUBSCRIPTION + '/ADD'
export const SUBSCRIPTION_PRODUCTS_ADD = SN_SUBSCRIPTION + '/PRODUCTS_ADD'
export const SUBSCRIPTION_COUPONS_ADD = SN_SUBSCRIPTION + '/COUPONS_ADD'